# Generated by Django 5.1.4 on 2026-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('tgID', models.IntegerField(unique=True)),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
