# Generated by Django 5.1.4 on 2026-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myuser_hmac_myuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
